language: python

python:
  - 3.5

env:
  global:
    - DJANGO_SETTINGS_MODULE="settings"
    - PYTHONPATH="/home/travis/build/sbywater/django-asana"
    - PIP_USE_MIRRORS=true
  matrix:
    -DJANGO_VERSION=1.11.5

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run manage.py test

after_success:
  - coveralls
