version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            # pip3 install requests
            python setup.py install
            # pipenv install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
